/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`last_quote_strategy_instrument_by_ticker`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LastQuoteStrategyInstrumentByTickerError {
    Status400(models::Orders400Response),
    Status401(models::Orders401Response),
    Status404(models::AccountById404Response),
    Status500(models::Orders500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`lasts_quotes_instruments_strategy`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LastsQuotesInstrumentsStrategyError {
    Status400(models::Orders400Response),
    Status401(models::Orders401Response),
    Status404(models::AccountById404Response),
    Status500(models::Orders500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`options_last_quote_strategy_instrument_by_ticker`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OptionsLastQuoteStrategyInstrumentByTickerError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`options_lasts_quotes_instruments_strategy`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OptionsLastsQuotesInstrumentsStrategyError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`options_search_quotes_instruments_strategy`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OptionsSearchQuotesInstrumentsStrategyError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`search_quotes_instruments_strategy`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SearchQuotesInstrumentsStrategyError {
    Status400(models::Orders400Response),
    Status401(models::Orders401Response),
    Status404(models::AccountById404Response),
    Status500(models::Orders500Response),
    UnknownValue(serde_json::Value),
}


/// This endpoint return the last quote received by the shareholder for the specific instrument and strategy. 
pub async fn last_quote_strategy_instrument_by_ticker(configuration: &configuration::Configuration, ticker: &str, strategy: &str) -> Result<models::V1StrategiesQuoteResponse, Error<LastQuoteStrategyInstrumentByTickerError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_ticker = ticker;
    let p_strategy = strategy;

    let uri_str = format!("{}/v1/eod/instrument/{ticker}/strategy/{strategy}/last", configuration.base_path, ticker=crate::apis::urlencode(p_ticker), strategy=crate::apis::urlencode(p_strategy));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::V1StrategiesQuoteResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::V1StrategiesQuoteResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<LastQuoteStrategyInstrumentByTickerError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn lasts_quotes_instruments_strategy(configuration: &configuration::Configuration, lasts_quotes_instruments_strategy_request: models::LastsQuotesInstrumentsStrategyRequest) -> Result<models::LastsQuotesInstrumentsStrategy200Response, Error<LastsQuotesInstrumentsStrategyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_lasts_quotes_instruments_strategy_request = lasts_quotes_instruments_strategy_request;

    let uri_str = format!("{}/v1/eod/instruments/strategy/lasts", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    req_builder = req_builder.json(&p_lasts_quotes_instruments_strategy_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::LastsQuotesInstrumentsStrategy200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::LastsQuotesInstrumentsStrategy200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<LastsQuotesInstrumentsStrategyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Options method is used to describe the communication options for the targeted resource.
pub async fn options_last_quote_strategy_instrument_by_ticker(configuration: &configuration::Configuration, ticker: &str, strategy: &str) -> Result<(), Error<OptionsLastQuoteStrategyInstrumentByTickerError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_ticker = ticker;
    let p_strategy = strategy;

    let uri_str = format!("{}/v1/eod/instrument/{ticker}/strategy/{strategy}/last", configuration.base_path, ticker=crate::apis::urlencode(p_ticker), strategy=crate::apis::urlencode(p_strategy));
    let mut req_builder = configuration.client.request(reqwest::Method::OPTIONS, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<OptionsLastQuoteStrategyInstrumentByTickerError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Options method is used to describe the communication options for the targeted resource.
pub async fn options_lasts_quotes_instruments_strategy(configuration: &configuration::Configuration, ) -> Result<(), Error<OptionsLastsQuotesInstrumentsStrategyError>> {

    let uri_str = format!("{}/v1/eod/instruments/strategy/lasts", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::OPTIONS, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<OptionsLastsQuotesInstrumentsStrategyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Options method is used to describe the communication options for the targeted resource.
pub async fn options_search_quotes_instruments_strategy(configuration: &configuration::Configuration, ) -> Result<(), Error<OptionsSearchQuotesInstrumentsStrategyError>> {

    let uri_str = format!("{}/v1/eod/instruments/strategies", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::OPTIONS, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<OptionsSearchQuotesInstrumentsStrategyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// This endpoint return a list of Quotes aggregated by interval (daily, weekly, monthly, quartely, yearly). 
pub async fn search_quotes_instruments_strategy(configuration: &configuration::Configuration, v1_screener_np_request: models::V1ScreenerNpRequest) -> Result<models::SearchQuotesInstrumentsStrategy200Response, Error<SearchQuotesInstrumentsStrategyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_v1_screener_np_request = v1_screener_np_request;

    let uri_str = format!("{}/v1/eod/instruments/strategies", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    req_builder = req_builder.json(&p_v1_screener_np_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::SearchQuotesInstrumentsStrategy200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::SearchQuotesInstrumentsStrategy200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SearchQuotesInstrumentsStrategyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

