/*
 * API Hartza Capital
 *
 * ## Welcome to the Hartza Capital API documentation  This comprehensive financial data API provides access to market information, portfolio management capabilities, and sophisticated trading tools.  For production use, an OAuth2 token is required. After authentication, you'll receive a token with a 15-minute lifespan.  When this period expires, please use your refresh token to obtain a new access token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Accounts200Response : AccountsListResponse is used to specify the response for the AccountsList API.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Accounts200Response {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::V1AccountResponse>>,
    /// Items is the total number of results.
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<i32>,
    /// TotalItems is the total number of results.
    #[serde(rename = "total_items", skip_serializing_if = "Option::is_none")]
    pub total_items: Option<i32>,
    /// Page is the current page number.
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<i32>,
    /// TotalPages is the total number of pages.
    #[serde(rename = "total_pages", skip_serializing_if = "Option::is_none")]
    pub total_pages: Option<i32>,
}

impl Accounts200Response {
    /// AccountsListResponse is used to specify the response for the AccountsList API.
    pub fn new() -> Accounts200Response {
        Accounts200Response {
            data: None,
            items: None,
            total_items: None,
            page: None,
            total_pages: None,
        }
    }
}

