/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BacktestInstrumentsRequest {
    #[serde(rename = "request", skip_serializing_if = "Option::is_none")]
    pub request: Option<Box<models::V1ScreenerNpRequest>>,
    /// Money is the amount of money to use for the backtest.
    #[serde(rename = "money", skip_serializing_if = "Option::is_none")]
    pub money: Option<f32>,
}

impl BacktestInstrumentsRequest {
    pub fn new() -> BacktestInstrumentsRequest {
        BacktestInstrumentsRequest {
            request: None,
            money: None,
        }
    }
}

