/*
 * API Hartza Capital
 *
 * ## Welcome to the Hartza Capital API documentation  This comprehensive financial data API provides access to market information, portfolio management capabilities, and sophisticated trading tools.  For production use, an OAuth2 token is required. After authentication, you'll receive a token with a 15-minute lifespan.  When this period expires, please use your refresh token to obtain a new access token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Backtest200ResponseStats {
    #[serde(rename = "trades", skip_serializing_if = "Option::is_none")]
    pub trades: Option<Box<models::Backtest200ResponseStatsTrades>>,
    #[serde(rename = "money", skip_serializing_if = "Option::is_none")]
    pub money: Option<Box<models::Backtest200ResponseStatsMoney>>,
}

impl Backtest200ResponseStats {
    pub fn new() -> Backtest200ResponseStats {
        Backtest200ResponseStats {
            trades: None,
            money: None,
        }
    }
}

