/*
 * API Hartza Capital
 *
 * ## Welcome to the Hartza Capital API documentation  This comprehensive financial data API provides access to market information, portfolio management capabilities, and sophisticated trading tools.  For production use, an OAuth2 token is required. After authentication, you'll receive a token with a 15-minute lifespan.  When this period expires, please use your refresh token to obtain a new access token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Backtest200ResponseStatsTrades {
    /// WinRate is the percentage of the trades that are profitable. It is the number of wins divided by the total number of trades.
    #[serde(rename = "win_rate", skip_serializing_if = "Option::is_none")]
    pub win_rate: Option<f64>,
    /// AverageWin is the average win of the strategy. It is the sum of the wins divided by the number of wins.
    #[serde(rename = "average_win", skip_serializing_if = "Option::is_none")]
    pub average_win: Option<f64>,
    /// AverageLoss is the average loss of the strategy. It is the sum of the losses divided by the number of losses.
    #[serde(rename = "average_loss", skip_serializing_if = "Option::is_none")]
    pub average_loss: Option<f64>,
    /// ProfitFactor is the ratio of the total profit to the total loss. It is the sum of the profits divided by the sum of the losses.
    #[serde(rename = "profit_factor", skip_serializing_if = "Option::is_none")]
    pub profit_factor: Option<f64>,
    /// RiskRewardRatio is the ratio of the average win to the average loss.
    #[serde(rename = "risk_reward_ratio", skip_serializing_if = "Option::is_none")]
    pub risk_reward_ratio: Option<f64>,
}

impl Backtest200ResponseStatsTrades {
    pub fn new() -> Backtest200ResponseStatsTrades {
        Backtest200ResponseStatsTrades {
            win_rate: None,
            average_win: None,
            average_loss: None,
            profit_factor: None,
            risk_reward_ratio: None,
        }
    }
}

