/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BacktestInstruments200ResponseStatsTrades {
    /// WinRate is the percentage of the trades that are profitable. It is the number of wins divided by the total number of trades.
    #[serde(rename = "win_rate", skip_serializing_if = "Option::is_none")]
    pub win_rate: Option<f32>,
    /// AverageWin is the average win of the strategy. It is the sum of the wins divided by the number of wins.
    #[serde(rename = "average_win", skip_serializing_if = "Option::is_none")]
    pub average_win: Option<f32>,
    /// AverageLoss is the average loss of the strategy. It is the sum of the losses divided by the number of losses.
    #[serde(rename = "average_loss", skip_serializing_if = "Option::is_none")]
    pub average_loss: Option<f32>,
    /// ProfitFactor is the ratio of the total profit to the total loss. It is the sum of the profits divided by the sum of the losses.
    #[serde(rename = "profit_factor", skip_serializing_if = "Option::is_none")]
    pub profit_factor: Option<f32>,
    /// RiskRewardRatio is the ratio of the average win to the average loss.
    #[serde(rename = "risk_reward_ratio", skip_serializing_if = "Option::is_none")]
    pub risk_reward_ratio: Option<f32>,
}

impl BacktestInstruments200ResponseStatsTrades {
    pub fn new() -> BacktestInstruments200ResponseStatsTrades {
        BacktestInstruments200ResponseStatsTrades {
            win_rate: None,
            average_win: None,
            average_loss: None,
            profit_factor: None,
            risk_reward_ratio: None,
        }
    }
}

