/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BacktestInstruments200ResponseStats {
    #[serde(rename = "trades", skip_serializing_if = "Option::is_none")]
    pub trades: Option<Box<models::BacktestInstruments200ResponseStatsTrades>>,
    #[serde(rename = "money", skip_serializing_if = "Option::is_none")]
    pub money: Option<Box<models::BacktestInstruments200ResponseStatsMoney>>,
}

impl BacktestInstruments200ResponseStats {
    pub fn new() -> BacktestInstruments200ResponseStats {
        BacktestInstruments200ResponseStats {
            trades: None,
            money: None,
        }
    }
}

