/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Country200ResponseEconomic {
    /// Currencies is the list of currencies used in the country.
    #[serde(rename = "currencies", skip_serializing_if = "Option::is_none")]
    pub currencies: Option<Vec<String>>,
    #[serde(rename = "exchanges", skip_serializing_if = "Option::is_none")]
    pub exchanges: Option<Vec<models::V1ExchangeBulkResponse>>,
    /// Indexes is the list of indexes used in the country.
    #[serde(rename = "indexes", skip_serializing_if = "Option::is_none")]
    pub indexes: Option<Vec<models::V1IndexResponse>>,
}

impl Country200ResponseEconomic {
    pub fn new() -> Country200ResponseEconomic {
        Country200ResponseEconomic {
            currencies: None,
            exchanges: None,
            indexes: None,
        }
    }
}

