/*
 * API Hartza Capital
 *
 * ## Welcome to the Hartza Capital API documentation  This comprehensive financial data API provides access to market information, portfolio management capabilities, and sophisticated trading tools.  For production use, an OAuth2 token is required. After authentication, you'll receive a token with a 15-minute lifespan.  When this period expires, please use your refresh token to obtain a new access token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateAccount409Response : Request could not be completed due to a conflict with the current state of the resource
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAccount409Response {
    /// Code is the status code.
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<i32>,
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    /// Details is a list of messages that provide additional information about the error.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, String>>,
}

impl CreateAccount409Response {
    /// Request could not be completed due to a conflict with the current state of the resource
    pub fn new() -> CreateAccount409Response {
        CreateAccount409Response {
            code: None,
            reason: None,
            message: None,
            metadata: None,
        }
    }
}

