/*
 * API Hartza Capital
 *
 * ## Welcome to the Hartza Capital API documentation  This comprehensive financial data API provides access to market information, portfolio management capabilities, and sophisticated trading tools.  For production use, an OAuth2 token is required. After authentication, you'll receive a token with a 15-minute lifespan.  When this period expires, please use your refresh token to obtain a new access token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilingsUs200ResponseAddress {
    /// TotalPages is the total number of pages.
    #[serde(rename = "street1", skip_serializing_if = "Option::is_none")]
    pub street1: Option<String>,
    /// TotalPages is the total number of pages.
    #[serde(rename = "street2", skip_serializing_if = "Option::is_none")]
    pub street2: Option<String>,
    /// TotalPages is the total number of pages.
    #[serde(rename = "city", skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    /// TotalPages is the total number of pages.
    #[serde(rename = "stateOrCountry", skip_serializing_if = "Option::is_none")]
    pub state_or_country: Option<String>,
    /// TotalPages is the total number of pages.
    #[serde(rename = "zipCode", skip_serializing_if = "Option::is_none")]
    pub zip_code: Option<String>,
    /// TotalPages is the total number of pages.
    #[serde(rename = "stateOrCountryDescription", skip_serializing_if = "Option::is_none")]
    pub state_or_country_description: Option<String>,
}

impl FilingsUs200ResponseAddress {
    pub fn new() -> FilingsUs200ResponseAddress {
        FilingsUs200ResponseAddress {
            street1: None,
            street2: None,
            city: None,
            state_or_country: None,
            zip_code: None,
            state_or_country_description: None,
        }
    }
}

