/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FilingsUs200Response : Filings US response format
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilingsUs200Response {
    /// Name of company
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "tickers", skip_serializing_if = "Option::is_none")]
    pub tickers: Option<Vec<String>>,
    #[serde(rename = "exchanges", skip_serializing_if = "Option::is_none")]
    pub exchanges: Option<Vec<String>>,
    /// TotalItems is the total number of results.
    #[serde(rename = "cik", skip_serializing_if = "Option::is_none")]
    pub cik: Option<String>,
    /// Page is the current page number.
    #[serde(rename = "sic", skip_serializing_if = "Option::is_none")]
    pub sic: Option<String>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<Box<models::FilingsUs200ResponseAddress>>,
    /// TotalPages is the total number of pages.
    #[serde(rename = "fiscalYearEnd", skip_serializing_if = "Option::is_none")]
    pub fiscal_year_end: Option<String>,
    #[serde(rename = "forms", skip_serializing_if = "Option::is_none")]
    pub forms: Option<std::collections::HashMap<String, Vec<models::FilingsUs200ResponseFormsValueInner>>>,
}

impl FilingsUs200Response {
    /// Filings US response format
    pub fn new() -> FilingsUs200Response {
        FilingsUs200Response {
            name: None,
            tickers: None,
            exchanges: None,
            cik: None,
            sic: None,
            address: None,
            fiscal_year_end: None,
            forms: None,
        }
    }
}

