/*
 * API Hartza Capital
 *
 * ## Welcome to the Hartza Capital API documentation  This comprehensive financial data API provides access to market information, portfolio management capabilities, and sophisticated trading tools.  For production use, an OAuth2 token is required. After authentication, you'll receive a token with a 15-minute lifespan.  When this period expires, please use your refresh token to obtain a new access token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilingsUs200ResponseFormsValueInnerObjectsPrincipal {
    /// Metadata is the metadata of the filing.
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<String>,
    /// Content is the content of the filing.
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
}

impl FilingsUs200ResponseFormsValueInnerObjectsPrincipal {
    pub fn new() -> FilingsUs200ResponseFormsValueInnerObjectsPrincipal {
        FilingsUs200ResponseFormsValueInnerObjectsPrincipal {
            metadata: None,
            content: None,
        }
    }
}

