/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilingsByCik200ResponseFormsValueInner {
    #[serde(rename = "objects", skip_serializing_if = "Option::is_none")]
    pub objects: Option<Box<models::FilingsByCik200ResponseFormsValueInnerObjects>>,
    /// AcceptanceDateTime is the date and time when the filing was accepted.
    #[serde(rename = "acceptanceDateTime", skip_serializing_if = "Option::is_none")]
    pub acceptance_date_time: Option<i64>,
    /// ReportDate is the date when the filing was reported.
    #[serde(rename = "reportDate", skip_serializing_if = "Option::is_none")]
    pub report_date: Option<i64>,
    /// FilingDate is the date when the filing was filed.
    #[serde(rename = "filingDate", skip_serializing_if = "Option::is_none")]
    pub filing_date: Option<i64>,
}

impl FilingsByCik200ResponseFormsValueInner {
    pub fn new() -> FilingsByCik200ResponseFormsValueInner {
        FilingsByCik200ResponseFormsValueInner {
            objects: None,
            acceptance_date_time: None,
            report_date: None,
            filing_date: None,
        }
    }
}

