/*
 * API Hartza Capital
 *
 * ## Welcome to the Hartza Capital API documentation  This comprehensive financial data API provides access to market information, portfolio management capabilities, and sophisticated trading tools.  For production use, an OAuth2 token is required. After authentication, you'll receive a token with a 15-minute lifespan.  When this period expires, please use your refresh token to obtain a new access token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilingsUs200ResponseFormsValueInnerObjects {
    #[serde(rename = "principal", skip_serializing_if = "Option::is_none")]
    pub principal: Option<Box<models::FilingsUs200ResponseFormsValueInnerObjectsPrincipal>>,
    /// Txt is the text file of the filing.
    #[serde(rename = "txt", skip_serializing_if = "Option::is_none")]
    pub txt: Option<String>,
    /// Xml is the xml file of the filing.
    #[serde(rename = "xml", skip_serializing_if = "Option::is_none")]
    pub xml: Option<String>,
}

impl FilingsUs200ResponseFormsValueInnerObjects {
    pub fn new() -> FilingsUs200ResponseFormsValueInnerObjects {
        FilingsUs200ResponseFormsValueInnerObjects {
            principal: None,
            txt: None,
            xml: None,
        }
    }
}

