/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilingsByCik200ResponseFormsValueInnerObjectsPrincipal {
    /// Metadata is the metadata of the filing.
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<String>,
    /// Content is the content of the filing.
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
}

impl FilingsByCik200ResponseFormsValueInnerObjectsPrincipal {
    pub fn new() -> FilingsByCik200ResponseFormsValueInnerObjectsPrincipal {
        FilingsByCik200ResponseFormsValueInnerObjectsPrincipal {
            metadata: None,
            content: None,
        }
    }
}

