/*
 * API Hartza Capital
 *
 * ## Welcome to the Hartza Capital API documentation  This comprehensive financial data API provides access to market information, portfolio management capabilities, and sophisticated trading tools.  For production use, an OAuth2 token is required. After authentication, you'll receive a token with a 15-minute lifespan.  When this period expires, please use your refresh token to obtain a new access token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilingsUs200ResponseFormsValueInner {
    #[serde(rename = "objects", skip_serializing_if = "Option::is_none")]
    pub objects: Option<Box<models::FilingsUs200ResponseFormsValueInnerObjects>>,
    /// AcceptanceDateTime is the date and time when the filing was accepted.
    #[serde(rename = "acceptanceDateTime", skip_serializing_if = "Option::is_none")]
    pub acceptance_date_time: Option<i64>,
    /// ReportDate is the date when the filing was reported.
    #[serde(rename = "reportDate", skip_serializing_if = "Option::is_none")]
    pub report_date: Option<i64>,
    /// FilingDate is the date when the filing was filed.
    #[serde(rename = "filingDate", skip_serializing_if = "Option::is_none")]
    pub filing_date: Option<i64>,
}

impl FilingsUs200ResponseFormsValueInner {
    pub fn new() -> FilingsUs200ResponseFormsValueInner {
        FilingsUs200ResponseFormsValueInner {
            objects: None,
            acceptance_date_time: None,
            report_date: None,
            filing_date: None,
        }
    }
}

