/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilterReport200ResponseAllocationOrdersValue {
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<f64>,
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<f64>,
    #[serde(rename = "percent", skip_serializing_if = "Option::is_none")]
    pub percent: Option<f64>,
    #[serde(rename = "diff", skip_serializing_if = "Option::is_none")]
    pub diff: Option<f64>,
}

impl FilterReport200ResponseAllocationOrdersValue {
    pub fn new() -> FilterReport200ResponseAllocationOrdersValue {
        FilterReport200ResponseAllocationOrdersValue {
            from: None,
            to: None,
            percent: None,
            diff: None,
        }
    }
}

