/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilterReport200ResponsePerformance {
    #[serde(rename = "hold", skip_serializing_if = "Option::is_none")]
    pub hold: Option<Vec<models::FilterReport200ResponsePerformanceHoldInner>>,
    #[serde(rename = "strategy", skip_serializing_if = "Option::is_none")]
    pub strategy: Option<Vec<models::FilterReport200ResponsePerformanceHoldInner>>,
}

impl FilterReport200ResponsePerformance {
    pub fn new() -> FilterReport200ResponsePerformance {
        FilterReport200ResponsePerformance {
            hold: None,
            strategy: None,
        }
    }
}

