/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilterReportById200ResponseGeographic {
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<std::collections::HashMap<String, models::FilterReportById200ResponseAssetValue>>,
    #[serde(rename = "region", skip_serializing_if = "Option::is_none")]
    pub region: Option<std::collections::HashMap<String, models::FilterReportById200ResponseAssetValue>>,
}

impl FilterReportById200ResponseGeographic {
    pub fn new() -> FilterReportById200ResponseGeographic {
        FilterReportById200ResponseGeographic {
            country: None,
            region: None,
        }
    }
}

