/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilterReport200ResponseCurrencyValue {
    /// Instruments is the list of instruments that the filter is applied to.
    #[serde(rename = "instruments", skip_serializing_if = "Option::is_none")]
    pub instruments: Option<Vec<i64>>,
    /// Percent is the percentage of the currency.
    #[serde(rename = "percent", skip_serializing_if = "Option::is_none")]
    pub percent: Option<f64>,
}

impl FilterReport200ResponseCurrencyValue {
    pub fn new() -> FilterReport200ResponseCurrencyValue {
        FilterReport200ResponseCurrencyValue {
            instruments: None,
            percent: None,
        }
    }
}

