/*
 * API Hartza Capital
 *
 * ## Welcome to the Hartza Capital API documentation  This comprehensive financial data API provides access to market information, portfolio management capabilities, and sophisticated trading tools.  For production use, an OAuth2 token is required. After authentication, you'll receive a token with a 15-minute lifespan.  When this period expires, please use your refresh token to obtain a new access token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Instrument200ResponseTax {
    /// CurrencyReport is the currency used for the tax report. ISO 4217 code.
    #[serde(rename = "currency_report", skip_serializing_if = "Option::is_none")]
    pub currency_report: Option<String>,
    /// YearEnd is the year end of the tax report. Ex: 12 for December.
    #[serde(rename = "year_end", skip_serializing_if = "Option::is_none")]
    pub year_end: Option<i32>,
}

impl Instrument200ResponseTax {
    pub fn new() -> Instrument200ResponseTax {
        Instrument200ResponseTax {
            currency_report: None,
            year_end: None,
        }
    }
}

