/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Orders200ResponseDataInnerPrice {
    /// Unit is the price per unit.
    #[serde(rename = "ask", skip_serializing_if = "Option::is_none")]
    pub ask: Option<f32>,
    /// Total is the total price.
    #[serde(rename = "bought", skip_serializing_if = "Option::is_none")]
    pub bought: Option<f32>,
    /// Commission is the commission of the orders.
    #[serde(rename = "commission", skip_serializing_if = "Option::is_none")]
    pub commission: Option<f32>,
    /// Currency is the currency of the price.
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
}

impl Orders200ResponseDataInnerPrice {
    pub fn new() -> Orders200ResponseDataInnerPrice {
        Orders200ResponseDataInnerPrice {
            ask: None,
            bought: None,
            commission: None,
            currency: None,
        }
    }
}

