/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Orders200ResponseDataInnerSize {
    /// Unit is the size per unit.
    #[serde(rename = "ask", skip_serializing_if = "Option::is_none")]
    pub ask: Option<f64>,
    /// Total is the total size.
    #[serde(rename = "bought", skip_serializing_if = "Option::is_none")]
    pub bought: Option<f64>,
}

impl Orders200ResponseDataInnerSize {
    pub fn new() -> Orders200ResponseDataInnerSize {
        Orders200ResponseDataInnerSize {
            ask: None,
            bought: None,
        }
    }
}

