/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Orders200Response : List Orders Response by account
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Orders200Response {
    /// Data is a list of orders.
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::Orders200ResponseDataInner>>,
    /// Total is the total number of orders.
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
}

impl Orders200Response {
    /// List Orders Response by account
    pub fn new() -> Orders200Response {
        Orders200Response {
            data: None,
            total: None,
        }
    }
}

