/*
 * API Hartza Capital
 *
 * ## Welcome to the Hartza Capital API documentation  This comprehensive financial data API provides access to market information, portfolio management capabilities, and sophisticated trading tools.  For production use, an OAuth2 token is required. After authentication, you'll receive a token with a 15-minute lifespan.  When this period expires, please use your refresh token to obtain a new access token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Orders200ResponseDataInnerSize {
    /// Unit is the size per unit.
    #[serde(rename = "ask", skip_serializing_if = "Option::is_none")]
    pub ask: Option<f64>,
    /// Total is the total size.
    #[serde(rename = "bought", skip_serializing_if = "Option::is_none")]
    pub bought: Option<f64>,
}

impl Orders200ResponseDataInnerSize {
    pub fn new() -> Orders200ResponseDataInnerSize {
        Orders200ResponseDataInnerSize {
            ask: None,
            bought: None,
        }
    }
}

