/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchAccountRequest {
    /// Name is a short description of account
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Description is the description of the account.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// CurrencyBase is the base currency of the account. It is the currency used to calculate the account value.
    #[serde(rename = "currency_base", skip_serializing_if = "Option::is_none")]
    pub currency_base: Option<String>,
    /// Ref of strategy apply on account.
    #[serde(rename = "strategy", skip_serializing_if = "Option::is_none")]
    pub strategy: Option<String>,
    /// MaxDrawdown is the maximum drawdown of the account. It is the maximum loss from a peak to a trough of a portfolio, before a new peak is attained.
    #[serde(rename = "max_drawdown", skip_serializing_if = "Option::is_none")]
    pub max_drawdown: Option<f64>,
    /// MaxPositions is the maximum number of positions in the account. It is the maximum number of positions that can be held in the account.
    #[serde(rename = "max_positions", skip_serializing_if = "Option::is_none")]
    pub max_positions: Option<i32>,
}

impl PatchAccountRequest {
    pub fn new() -> PatchAccountRequest {
        PatchAccountRequest {
            name: None,
            description: None,
            currency_base: None,
            strategy: None,
            max_drawdown: None,
            max_positions: None,
        }
    }
}

