/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PortfoliosQuotes200ResponseDistributionInner {
    /// Max is the maximum value of the histogram.
    #[serde(rename = "max", skip_serializing_if = "Option::is_none")]
    pub max: Option<f64>,
    /// Min is the minimum value of the histogram.
    #[serde(rename = "min", skip_serializing_if = "Option::is_none")]
    pub min: Option<f64>,
    /// Count is the number of values in the histogram.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
}

impl PortfoliosQuotes200ResponseDistributionInner {
    pub fn new() -> PortfoliosQuotes200ResponseDistributionInner {
        PortfoliosQuotes200ResponseDistributionInner {
            max: None,
            min: None,
            count: None,
        }
    }
}

