/*
 * API Hartza Capital
 *
 * ## Welcome to the Hartza Capital API documentation  This comprehensive financial data API provides access to market information, portfolio management capabilities, and sophisticated trading tools.  For production use, an OAuth2 token is required. After authentication, you'll receive a token with a 15-minute lifespan.  When this period expires, please use your refresh token to obtain a new access token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PortfoliosQuotes200Response {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::V1QuoteResponse>>,
    /// Distribution is a list of values for the histogram.
    #[serde(rename = "distribution", skip_serializing_if = "Option::is_none")]
    pub distribution: Option<Vec<models::PortfoliosQuotes200ResponseDistributionInner>>,
    /// Total is the total number of results.
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
}

impl PortfoliosQuotes200Response {
    pub fn new() -> PortfoliosQuotes200Response {
        PortfoliosQuotes200Response {
            data: None,
            distribution: None,
            total: None,
        }
    }
}

