/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PortfoliosHistogram200ResponseDataPerformanceInner {
    /// Change is the change in the value of the histogram.
    #[serde(rename = "change", skip_serializing_if = "Option::is_none")]
    pub change: Option<f64>,
    /// Close is the closing value of the security.
    #[serde(rename = "close", skip_serializing_if = "Option::is_none")]
    pub close: Option<f64>,
    /// MarketCap is the market capitalization of the security.
    #[serde(rename = "market_cap", skip_serializing_if = "Option::is_none")]
    pub market_cap: Option<f64>,
    /// Value is the value of the change.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<f64>,
    /// CreatedAt is the time at which the change was created.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
}

impl PortfoliosHistogram200ResponseDataPerformanceInner {
    pub fn new() -> PortfoliosHistogram200ResponseDataPerformanceInner {
        PortfoliosHistogram200ResponseDataPerformanceInner {
            change: None,
            close: None,
            market_cap: None,
            value: None,
            created_at: None,
        }
    }
}

