/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchQuotesPortfolioHistogram200ResponseData {
    /// Changes is a list of changes for the histogram.
    #[serde(rename = "performance", skip_serializing_if = "Option::is_none")]
    pub performance: Option<Vec<models::SearchQuotesPortfolioHistogram200ResponseDataPerformanceInner>>,
    /// Histogram is a list of values for the histogram.
    #[serde(rename = "distribution", skip_serializing_if = "Option::is_none")]
    pub distribution: Option<Vec<models::SearchQuotesPortfolioHistogram200ResponseDataDistributionInner>>,
}

impl SearchQuotesPortfolioHistogram200ResponseData {
    pub fn new() -> SearchQuotesPortfolioHistogram200ResponseData {
        SearchQuotesPortfolioHistogram200ResponseData {
            performance: None,
            distribution: None,
        }
    }
}

