/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchQuotesPortfolioHistogram200Response : HistogramResponse is used to specify the response for the Histogram API.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchQuotesPortfolioHistogram200Response {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<models::SearchQuotesPortfolioHistogram200ResponseData>>,
    /// Total is the total number of results.
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
}

impl SearchQuotesPortfolioHistogram200Response {
    /// HistogramResponse is used to specify the response for the Histogram API.
    pub fn new() -> SearchQuotesPortfolioHistogram200Response {
        SearchQuotesPortfolioHistogram200Response {
            data: None,
            total: None,
        }
    }
}

