/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SharesOrder : SharesOrder is used to specify the order of the shares.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SharesOrder {
    /// Min is the minimum number of shares that can be ordered.
    #[serde(rename = "min", skip_serializing_if = "Option::is_none")]
    pub min: Option<f64>,
    /// Increment is the minimum increment of the order.
    #[serde(rename = "increment", skip_serializing_if = "Option::is_none")]
    pub increment: Option<f64>,
}

impl SharesOrder {
    /// SharesOrder is used to specify the order of the shares.
    pub fn new() -> SharesOrder {
        SharesOrder {
            min: None,
            increment: None,
        }
    }
}

