/*
 * API Hartza Capital
 *
 * ## Welcome to the Hartza Capital API documentation  This comprehensive financial data API provides access to market information, portfolio management capabilities, and sophisticated trading tools.  For production use, an OAuth2 token is required. After authentication, you'll receive a token with a 15-minute lifespan.  When this period expires, please use your refresh token to obtain a new access token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StatsResponsePrice : Price is used to show statistics about the price of the security.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatsResponsePrice {
    /// MarketCapUSD is the market capitalization of the security in USD.
    #[serde(rename = "market_cap_usd", skip_serializing_if = "Option::is_none")]
    pub market_cap_usd: Option<i64>,
    /// Start is the price at the beginning of the year.
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<f64>,
    /// MinAnnual is the minimum price of the security in the year.
    #[serde(rename = "min_annual", skip_serializing_if = "Option::is_none")]
    pub min_annual: Option<f64>,
    /// MaxAnnual is the maximum price of the security in the year.
    #[serde(rename = "max_annual", skip_serializing_if = "Option::is_none")]
    pub max_annual: Option<f64>,
    /// ReturnYear is the return of the security in the year.
    #[serde(rename = "return_year", skip_serializing_if = "Option::is_none")]
    pub return_year: Option<f64>,
    /// Beta5y is the beta of the security over the last 5 years.
    #[serde(rename = "beta5y", skip_serializing_if = "Option::is_none")]
    pub beta5y: Option<f64>,
}

impl StatsResponsePrice {
    /// Price is used to show statistics about the price of the security.
    pub fn new() -> StatsResponsePrice {
        StatsResponsePrice {
            market_cap_usd: None,
            start: None,
            min_annual: None,
            max_annual: None,
            return_year: None,
            beta5y: None,
        }
    }
}

