/*
 * API Hartza Capital
 *
 * ## Welcome to the Hartza Capital API documentation  This comprehensive financial data API provides access to market information, portfolio management capabilities, and sophisticated trading tools.  For production use, an OAuth2 token is required. After authentication, you'll receive a token with a 15-minute lifespan.  When this period expires, please use your refresh token to obtain a new access token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StatsResponseVolumes : Volumes is used to show statistics about the volume of the security.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatsResponseVolumes {
    /// Avg10d is the average volume over the last 10 days.
    #[serde(rename = "avg_10d", skip_serializing_if = "Option::is_none")]
    pub avg_10d: Option<i64>,
    /// Avg30d is the average volume over the last 30 days.
    #[serde(rename = "avg_30d", skip_serializing_if = "Option::is_none")]
    pub avg_30d: Option<i64>,
    /// Avg90d is the average volume over the last 90 days.
    #[serde(rename = "avg_90d", skip_serializing_if = "Option::is_none")]
    pub avg_90d: Option<i64>,
    /// Ratio is the ratio of the volume.
    #[serde(rename = "ratio", skip_serializing_if = "Option::is_none")]
    pub ratio: Option<f64>,
}

impl StatsResponseVolumes {
    /// Volumes is used to show statistics about the volume of the security.
    pub fn new() -> StatsResponseVolumes {
        StatsResponseVolumes {
            avg_10d: None,
            avg_30d: None,
            avg_90d: None,
            ratio: None,
        }
    }
}

