/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Time200Response : GetTimeResponse is used to specify the response for the GetTime API.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Time200Response {
    /// Timestamp is the current time in seconds.
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i64>,
    /// Timezone is the timezone of the current time.
    #[serde(rename = "timezone", skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    /// Date is the current date RFC3339.
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
}

impl Time200Response {
    /// GetTimeResponse is used to specify the response for the GetTime API.
    pub fn new() -> Time200Response {
        Time200Response {
            timestamp: None,
            timezone: None,
            date: None,
        }
    }
}

