/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// User200ResponseContact : Contact is the contact information of the user.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User200ResponseContact {
    /// Email is the email of the user.
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// EmailVerified is a boolean value that indicates if the email of the user is verified.
    #[serde(rename = "email_verified", skip_serializing_if = "Option::is_none")]
    pub email_verified: Option<bool>,
    /// Phone is the phone number of the user.
    #[serde(rename = "phone", skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    /// Address is the address of the user.
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// City is the city of the user.
    #[serde(rename = "city", skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    /// PostalCode is the postal code of the user.
    #[serde(rename = "postal_code", skip_serializing_if = "Option::is_none")]
    pub postal_code: Option<String>,
    /// Country is the country of the user.
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
}

impl User200ResponseContact {
    /// Contact is the contact information of the user.
    pub fn new() -> User200ResponseContact {
        User200ResponseContact {
            email: None,
            email_verified: None,
            phone: None,
            address: None,
            city: None,
            postal_code: None,
            country: None,
        }
    }
}

