/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1AccountResponse : ListAccountsResponseResult is used to specify the response for the ListAccounts API.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1AccountResponse {
    /// Ref is the unique identifier for the account.
    #[serde(rename = "ref", skip_serializing_if = "Option::is_none")]
    pub r#ref: Option<String>,
    /// Name is the name of the account.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Description of account.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// CurrencyBase is the base currency of the account. It is the currency used to calculate the account value.
    #[serde(rename = "currency_base", skip_serializing_if = "Option::is_none")]
    pub currency_base: Option<String>,
    /// Status is the status of the account. It is the status of the account.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// CreatedAt is the creation date of the account.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
    /// UpdatedAt is the last update date of the account.
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i64>,
}

impl V1AccountResponse {
    /// ListAccountsResponseResult is used to specify the response for the ListAccounts API.
    pub fn new() -> V1AccountResponse {
        V1AccountResponse {
            r#ref: None,
            name: None,
            description: None,
            currency_base: None,
            status: None,
            created_at: None,
            updated_at: None,
        }
    }
}

