/*
 * API Hartza Capital
 *
 * ## Welcome to the Hartza Capital API documentation  This comprehensive financial data API provides access to market information, portfolio management capabilities, and sophisticated trading tools.  For production use, an OAuth2 token is required. After authentication, you'll receive a token with a 15-minute lifespan.  When this period expires, please use your refresh token to obtain a new access token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1AccountResponse : Contains comprehensive account information including identification, configuration settings, base currency, account status, and creation/modification timestamps.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1AccountResponse {
    /// Ref is the unique identifier for the account.
    #[serde(rename = "ref", skip_serializing_if = "Option::is_none")]
    pub r#ref: Option<String>,
    /// Name is the name of the account.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Description of account.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// CurrencyBase is the base currency of the account. It is the currency used to calculate the account value.
    #[serde(rename = "currency_base", skip_serializing_if = "Option::is_none")]
    pub currency_base: Option<String>,
    /// Status is the status of the account. It is the status of the account.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// CreatedAt is the creation date of the account.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
    /// Timestamp (in Unix epoch seconds) when this resource was last modified.
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i64>,
}

impl V1AccountResponse {
    /// Contains comprehensive account information including identification, configuration settings, base currency, account status, and creation/modification timestamps.
    pub fn new() -> V1AccountResponse {
        V1AccountResponse {
            r#ref: None,
            name: None,
            description: None,
            currency_base: None,
            status: None,
            created_at: None,
            updated_at: None,
        }
    }
}

