/*
 * API Hartza Capital
 *
 * ## Welcome to the Hartza Capital API documentation  This comprehensive financial data API provides access to market information, portfolio management capabilities, and sophisticated trading tools.  For production use, an OAuth2 token is required. After authentication, you'll receive a token with a 15-minute lifespan.  When this period expires, please use your refresh token to obtain a new access token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1CurrencyResponse : GetResponseCurrency is used to specify the response for the GetCurrency API.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1CurrencyResponse {
    /// Ticker is the unique identifier for the currency. ISO 4217 code.
    #[serde(rename = "ticker", skip_serializing_if = "Option::is_none")]
    pub ticker: Option<String>,
    /// IMFReserve is a boolean value that indicates if the currency is a reserve currency of the International Monetary Fund.
    #[serde(rename = "imf_reserve", skip_serializing_if = "Option::is_none")]
    pub imf_reserve: Option<bool>,
    #[serde(rename = "central_bank", skip_serializing_if = "Option::is_none")]
    pub central_bank: Option<Box<models::V1CurrencyResponseCentralBank>>,
    /// Exchanges is the list of exchanges used in the country.
    #[serde(rename = "exchanges", skip_serializing_if = "Option::is_none")]
    pub exchanges: Option<Vec<models::V1ExchangesBulkResponse>>,
    /// Countries is the list of countries using the currency.
    #[serde(rename = "countries", skip_serializing_if = "Option::is_none")]
    pub countries: Option<Vec<models::V1CountryBulkResponse>>,
}

impl V1CurrencyResponse {
    /// GetResponseCurrency is used to specify the response for the GetCurrency API.
    pub fn new() -> V1CurrencyResponse {
        V1CurrencyResponse {
            ticker: None,
            imf_reserve: None,
            central_bank: None,
            exchanges: None,
            countries: None,
        }
    }
}

