/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1DividendResponse : SearchDividendsResponseResult is used to specify the response for the SearchDividends API.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1DividendResponse {
    /// Value is the value of the dividend.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<f64>,
    /// Yield is the yield of the dividend.
    #[serde(rename = "yield", skip_serializing_if = "Option::is_none")]
    pub r#yield: Option<f64>,
    /// DeclarationDate is the date at which the dividend was declared.
    #[serde(rename = "declaration_date", skip_serializing_if = "Option::is_none")]
    pub declaration_date: Option<i64>,
    /// RecordDate is the date at which the dividend was recorded.
    #[serde(rename = "record_date", skip_serializing_if = "Option::is_none")]
    pub record_date: Option<i64>,
    /// PaymentDate is the date at which the dividend was paid.
    #[serde(rename = "payment_date", skip_serializing_if = "Option::is_none")]
    pub payment_date: Option<i64>,
    /// CreatedAt is the time at which the quote was created.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
}

impl V1DividendResponse {
    /// SearchDividendsResponseResult is used to specify the response for the SearchDividends API.
    pub fn new() -> V1DividendResponse {
        V1DividendResponse {
            value: None,
            r#yield: None,
            declaration_date: None,
            record_date: None,
            payment_date: None,
            created_at: None,
        }
    }
}

