/*
 * API Hartza Capital
 *
 * ## Welcome to the Hartza Capital API documentation  This comprehensive financial data API provides access to market information, portfolio management capabilities, and sophisticated trading tools.  For production use, an OAuth2 token is required. After authentication, you'll receive a token with a 15-minute lifespan.  When this period expires, please use your refresh token to obtain a new access token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1IndexResponse : Provides comprehensive information about a market index, including its identifier, name, constituent instruments, and performance metrics over various time periods.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1IndexResponse {
    /// Unique identifier symbol for this financial instrument, following standard market conventions.
    #[serde(rename = "ticker", skip_serializing_if = "Option::is_none")]
    pub ticker: Option<String>,
    /// Name is the name of the index.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl V1IndexResponse {
    /// Provides comprehensive information about a market index, including its identifier, name, constituent instruments, and performance metrics over various time periods.
    pub fn new() -> V1IndexResponse {
        V1IndexResponse {
            ticker: None,
            name: None,
        }
    }
}

