/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1MacroCalendarResponse : GetFilterResponse is used to specify the response for the GetFilter API.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1MacroCalendarResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::V1MacroCalendarResponseDataInner>>,
    /// Total is the total number of events.
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
}

impl V1MacroCalendarResponse {
    /// GetFilterResponse is used to specify the response for the GetFilter API.
    pub fn new() -> V1MacroCalendarResponse {
        V1MacroCalendarResponse {
            data: None,
            total: None,
        }
    }
}

