/*
 * API Hartza Capital
 *
 * ## Welcome to the Hartza Capital API documentation  This comprehensive financial data API provides access to market information, portfolio management capabilities, and sophisticated trading tools.  For production use, an OAuth2 token is required. After authentication, you'll receive a token with a 15-minute lifespan.  When this period expires, please use your refresh token to obtain a new access token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1MacroCalendarResponse : Contains structured data about macroeconomic calendar events, providing comprehensive information about scheduled economic announcements, their significance levels, and timing details.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1MacroCalendarResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::V1MacroCalendarResponseDataInner>>,
    /// Total is the total number of events.
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
}

impl V1MacroCalendarResponse {
    /// Contains structured data about macroeconomic calendar events, providing comprehensive information about scheduled economic announcements, their significance levels, and timing details.
    pub fn new() -> V1MacroCalendarResponse {
        V1MacroCalendarResponse {
            data: None,
            total: None,
        }
    }
}

