/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1QuoteResponse {
    /// Change is the change in the price of the security.
    #[serde(rename = "change", skip_serializing_if = "Option::is_none")]
    pub change: Option<f64>,
    /// MarketCap is the market capitalization of the security.
    #[serde(rename = "market_cap", skip_serializing_if = "Option::is_none")]
    pub market_cap: Option<f64>,
    /// Open is the opening price of the security.
    #[serde(rename = "open", skip_serializing_if = "Option::is_none")]
    pub open: Option<f64>,
    /// High is the high price of the security.
    #[serde(rename = "high", skip_serializing_if = "Option::is_none")]
    pub high: Option<f64>,
    /// Low is the low price of the security.
    #[serde(rename = "low", skip_serializing_if = "Option::is_none")]
    pub low: Option<f64>,
    /// Close is the closing price of the security.
    #[serde(rename = "close", skip_serializing_if = "Option::is_none")]
    pub close: Option<f64>,
    /// Volume is the volume of the security.
    #[serde(rename = "volume", skip_serializing_if = "Option::is_none")]
    pub volume: Option<i64>,
    /// CreatedAt is the date and time of the quote.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
}

impl V1QuoteResponse {
    pub fn new() -> V1QuoteResponse {
        V1QuoteResponse {
            change: None,
            market_cap: None,
            open: None,
            high: None,
            low: None,
            close: None,
            volume: None,
            created_at: None,
        }
    }
}

