/*
 * API Hartza Capital
 *
 * ## Welcome to the Hartza Capital API documentation  This comprehensive financial data API provides access to market information, portfolio management capabilities, and sophisticated trading tools.  For production use, an OAuth2 token is required. After authentication, you'll receive a token with a 15-minute lifespan.  When this period expires, please use your refresh token to obtain a new access token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1SplitResponse : SearchSplitsResponseResult is used to specify the response for the SearchSplits API.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1SplitResponse {
    /// Ref is the unique identifier of instrument.
    #[serde(rename = "ref", skip_serializing_if = "Option::is_none")]
    pub r#ref: Option<String>,
    /// From is the number of shares before the split.
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<f64>,
    /// To is the number of shares after the split.
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<f64>,
    /// Coef is the coefficient of the split.
    #[serde(rename = "coef", skip_serializing_if = "Option::is_none")]
    pub coef: Option<f64>,
    /// Timestamp (in Unix epoch seconds) when this resource was initially created in the system.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
}

impl V1SplitResponse {
    /// SearchSplitsResponseResult is used to specify the response for the SearchSplits API.
    pub fn new() -> V1SplitResponse {
        V1SplitResponse {
            r#ref: None,
            from: None,
            to: None,
            coef: None,
            created_at: None,
        }
    }
}

