/*
 * API Hartza Capital
 *
 * ## Welcome to the Hartza Capital API documentation  This comprehensive financial data API provides access to market information, portfolio management capabilities, and sophisticated trading tools.  For production use, an OAuth2 token is required. After authentication, you'll receive a token with a 15-minute lifespan.  When this period expires, please use your refresh token to obtain a new access token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1ScreenerPagination : ScreenerRequestSort is used to specify the sort for a search.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ScreenerPagination {
    /// Items is the number of items per page.
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<i32>,
    /// Page is the current page number.
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<i32>,
}

impl V1ScreenerPagination {
    /// ScreenerRequestSort is used to specify the sort for a search.
    pub fn new() -> V1ScreenerPagination {
        V1ScreenerPagination {
            items: None,
            page: None,
        }
    }
}

