/*
 * API Hartza Capital
 *
 * ## Welcome to the Hartza Capital API documentation  This comprehensive financial data API provides access to market information, portfolio management capabilities, and sophisticated trading tools.  For production use, an OAuth2 token is required. After authentication, you'll receive a token with a 15-minute lifespan.  When this period expires, please use your refresh token to obtain a new access token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1ScreenerSort : ScreenerRequestSort is used to specify the sort for a search.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ScreenerSort {
    /// Field is the field to sort by.
    #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
    pub field: Option<Field>,
    /// Orientation is the direction of the sort.
    #[serde(rename = "direction", skip_serializing_if = "Option::is_none")]
    pub direction: Option<Direction>,
}

impl V1ScreenerSort {
    /// ScreenerRequestSort is used to specify the sort for a search.
    pub fn new() -> V1ScreenerSort {
        V1ScreenerSort {
            field: None,
            direction: None,
        }
    }
}
/// Field is the field to sort by.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Field {
    #[serde(rename = "time")]
    Time,
    #[serde(rename = "id")]
    Id,
    #[serde(rename = "market_cap_usd")]
    MarketCapUsd,
    #[serde(rename = "ticker")]
    Ticker,
    #[serde(rename = "change")]
    Change,
}

impl Default for Field {
    fn default() -> Field {
        Self::Time
    }
}
/// Orientation is the direction of the sort.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Direction {
    #[serde(rename = "ASC")]
    Asc,
    #[serde(rename = "DESC")]
    Desc,
}

impl Default for Direction {
    fn default() -> Direction {
        Self::Asc
    }
}

