/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1StrategiesQuoteResponse : SearchStrategiesQuotesResponseResult is used to specify the result for the SearchStrategiesQuotes API.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1StrategiesQuoteResponse {
    /// Status is the status of the strategy. It is the status of the strategy.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Open is the opening price of the security.
    #[serde(rename = "open", skip_serializing_if = "Option::is_none")]
    pub open: Option<f32>,
    /// Currently is the current price of the security.
    #[serde(rename = "close", skip_serializing_if = "Option::is_none")]
    pub close: Option<f32>,
    /// CreatedAt is the date and time of the quote.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
}

impl V1StrategiesQuoteResponse {
    /// SearchStrategiesQuotesResponseResult is used to specify the result for the SearchStrategiesQuotes API.
    pub fn new() -> V1StrategiesQuoteResponse {
        V1StrategiesQuoteResponse {
            status: None,
            open: None,
            close: None,
            created_at: None,
        }
    }
}

