/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1SplitResponse : SearchSplitsResponseResult is used to specify the response for the SearchSplits API.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1SplitResponse {
    /// Ref is the unique identifier of instrument.
    #[serde(rename = "ref", skip_serializing_if = "Option::is_none")]
    pub r#ref: Option<String>,
    /// From is the number of shares before the split.
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<f64>,
    /// To is the number of shares after the split.
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<f64>,
    /// Coef is the coefficient of the split.
    #[serde(rename = "coef", skip_serializing_if = "Option::is_none")]
    pub coef: Option<f64>,
    /// CreatedAt is the time at which the quote was created.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
}

impl V1SplitResponse {
    /// SearchSplitsResponseResult is used to specify the response for the SearchSplits API.
    pub fn new() -> V1SplitResponse {
        V1SplitResponse {
            r#ref: None,
            from: None,
            to: None,
            coef: None,
            created_at: None,
        }
    }
}

