/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1WatchlistResponse : GetFilterResponse is used to specify the response for the GetFilter API.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1WatchlistResponse {
    /// Ticker is the unique identifier for the filter.
    #[serde(rename = "ticker", skip_serializing_if = "Option::is_none")]
    pub ticker: Option<String>,
    /// Description is the description of the filter.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Filters is a list of filters.
    #[serde(rename = "filters", skip_serializing_if = "Option::is_none")]
    pub filters: Option<Vec<models::V1ScreenerFilter>>,
    #[serde(rename = "sort", skip_serializing_if = "Option::is_none")]
    pub sort: Option<Box<models::V1ScreenerSort>>,
    #[serde(rename = "results", skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<models::V1SearchResponse>>,
    #[serde(rename = "stats", skip_serializing_if = "Option::is_none")]
    pub stats: Option<Box<models::V1WatchlistResponseStats>>,
    /// UUID of report
    #[serde(rename = "report_id", skip_serializing_if = "Option::is_none")]
    pub report_id: Option<uuid::Uuid>,
    /// CreatedAt is the creation date of the filter.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
    /// UpdatedAt is the last update date of the filter.
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i64>,
}

impl V1WatchlistResponse {
    /// GetFilterResponse is used to specify the response for the GetFilter API.
    pub fn new() -> V1WatchlistResponse {
        V1WatchlistResponse {
            ticker: None,
            description: None,
            filters: None,
            sort: None,
            results: None,
            stats: None,
            report_id: None,
            created_at: None,
            updated_at: None,
        }
    }
}

