/*
 * API Hartza Capital
 *
 * ## Welcome to the Hartza Capital API documentation  This comprehensive financial data API provides access to market information, portfolio management capabilities, and sophisticated trading tools.  For production use, an OAuth2 token is required. After authentication, you'll receive a token with a 15-minute lifespan.  When this period expires, please use your refresh token to obtain a new access token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1WatchlistResponse : Represents a customized collection of financial instruments that users can monitor, including filtering criteria, sorting preferences, and statistical summaries of the included securities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1WatchlistResponse {
    /// Ticker is the unique identifier for the watchlist.
    #[serde(rename = "ticker", skip_serializing_if = "Option::is_none")]
    pub ticker: Option<String>,
    /// Description is the description of the filter.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// List of instruments in the watchlist.
    #[serde(rename = "filters", skip_serializing_if = "Option::is_none")]
    pub filters: Option<Vec<models::V1ScreenerFilter>>,
    #[serde(rename = "sort", skip_serializing_if = "Option::is_none")]
    pub sort: Option<Box<models::V1ScreenerSort>>,
    #[serde(rename = "results", skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<models::V1SearchResponse>>,
    #[serde(rename = "stats", skip_serializing_if = "Option::is_none")]
    pub stats: Option<Box<models::V1WatchlistResponseStats>>,
    /// UUID of report generated for the watchlist.
    #[serde(rename = "report_id", skip_serializing_if = "Option::is_none")]
    pub report_id: Option<uuid::Uuid>,
    /// Timestamp (in Unix epoch seconds) when this resource was initially created in the system.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
    /// Timestamp (in Unix epoch seconds) when this resource was last modified.
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i64>,
}

impl V1WatchlistResponse {
    /// Represents a customized collection of financial instruments that users can monitor, including filtering criteria, sorting preferences, and statistical summaries of the included securities.
    pub fn new() -> V1WatchlistResponse {
        V1WatchlistResponse {
            ticker: None,
            description: None,
            filters: None,
            sort: None,
            results: None,
            stats: None,
            report_id: None,
            created_at: None,
            updated_at: None,
        }
    }
}

