/*
 * API Hartza Capital
 *
 * ## Welcome to the Hartza Capital API documentation  This comprehensive financial data API provides access to market information, portfolio management capabilities, and sophisticated trading tools.  For production use, an OAuth2 token is required. After authentication, you'll receive a token with a 15-minute lifespan.  When this period expires, please use your refresh token to obtain a new access token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WatchlistReport200ResponseCurrencyValue {
    /// Instruments is the list of instruments that the filter is applied to.
    #[serde(rename = "instruments", skip_serializing_if = "Option::is_none")]
    pub instruments: Option<Vec<i64>>,
    /// Percent is the percentage of the currency.
    #[serde(rename = "percent", skip_serializing_if = "Option::is_none")]
    pub percent: Option<f64>,
}

impl WatchlistReport200ResponseCurrencyValue {
    pub fn new() -> WatchlistReport200ResponseCurrencyValue {
        WatchlistReport200ResponseCurrencyValue {
            instruments: None,
            percent: None,
        }
    }
}

