/*
 * API Hartza Capital
 *
 * ## Welcome on the Hartza Capital API documentation  For production use, you must obtain an oAuth2 token. To have this token, please authenticate and use your token.    The token has a lifespan of 15 minutes, after this period please renew it with the refresh token. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hartza.capital
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WatchlistReport200ResponseAssetValue {
    #[serde(rename = "instruments", skip_serializing_if = "Option::is_none")]
    pub instruments: Option<Vec<i64>>,
    #[serde(rename = "percent", skip_serializing_if = "Option::is_none")]
    pub percent: Option<f64>,
}

impl WatchlistReport200ResponseAssetValue {
    pub fn new() -> WatchlistReport200ResponseAssetValue {
        WatchlistReport200ResponseAssetValue {
            instruments: None,
            percent: None,
        }
    }
}

